name: Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check syntax
      run: |
        python -m py_compile app.py caldav_client.py deepseek_parser.py calendar_agent_deepseek.py

    - name: Test imports
      run: |
        python -c "from caldav_client import AppleCalendarClient; print('✅ CalDAV client import successful')"
        python -c "from deepseek_parser import DeepSeekCalendarParser; print('✅ DeepSeek parser import successful')"
        python -c "from calendar_agent_deepseek import CalendarAgentDeepSeek; print('✅ Calendar agent import successful')"

    - name: Run basic tests
      run: |
        python test_agent.py
        python check_env.py